inp=open("tut1q3i.dat","r")
x1=float(inp.readline())
y1=float(inp.readline())
x2=float(inp.readline())
y2=float(inp.readline())
x=float(inp.readline())
y = y1 +(y2 - y1)/(x2 - x1)*(x - x1)
outp=open("tut1q3o.txt","w")
outp.write("y = "+str(y))
inp.close()
outp.close()